### ISSUE TITLE
Add new Staff Function

### ISSUE THREAD

**Issue by luqmanhuzaimin** [hapidji96/endgame-dentalia-clinic#13]
Please add new function which to add new staff

**Comment by hapidji96** [comment]
Changes have been made.

This is the screenshot.
![image](https://user-images.githubusercontent.com/61451245/83264195-534e0100-a1f2-11ea-9ab0-ff16ee020de9.png)

This is the code.
[CR002-Add Staff.txt](https://github.com/hapidji96/endgame-dentalia-clinic/files/4701975/CR002-Add.Staff.txt)
