### ISSUE TITLE
Delete Staff Function

### ISSUE THREAD

**Issue by luqmanhuzaimin** [hapidji96/endgame-dentalia-clinic#14]
Please add new function which to add new staff

**Comment by hapidji96** [comment]
Changes have been made.

This is the screenshot.
![image](https://user-images.githubusercontent.com/61451245/83264035-1b46be00-a1f2-11ea-8992-4e3c42d0b80c.png)

This is the code.
[CR003-Delete Staff.txt](https://github.com/hapidji96/endgame-dentalia-clinic/files/4701968/CR003-Delete.Staff.txt)
