### ISSUE TITLE
Delete service request for Staff

### ISSUE THREAD

**Issue by luqmanhuzaimin** [hapidji96/endgame-dentalia-clinic#15]
Please make the enhancement

**Comment by fazlinsyakina** [comment]
Changes has been made.

Screenshot of the change.
<img width="193" alt="CR004-Delete Service Request" src="https://user-images.githubusercontent.com/54977960/82996266-49cc6980-a037-11ea-8122-31ddefed712a.png">

Code of the change.
[CR004-Delete Service Request.txt](https://github.com/hapidji96/endgame-dentalia-clinic/files/4687520/CR004-Delete.Service.Request.txt)
