### ISSUE TITLE
Add a new function, which is delete patient button

### ISSUE THREAD

**Issue by luqmanhuzaimin** [hapidji96/endgame-dentalia-clinic#16]
Please make the enhancement

**Comment by fazlinsyakina** [comment]
Changes has been made.

Screenshot of the change.
<img width="164" alt="CR005-Delete Patient" src="https://user-images.githubusercontent.com/54977960/82997115-89478580-a038-11ea-9b61-73c1fef90494.png">

Code of the change.
[CR005-Delete Patient.txt](https://github.com/hapidji96/endgame-dentalia-clinic/files/4687538/CR005-Delete.Patient.txt)
