### ISSUE TITLE
Add a new function, which is register button

### ISSUE THREAD

**Issue by luqmanhuzaimin** [hapidji96/endgame-dentalia-clinic#19]
Please make the enhancement

**Comment by amirulwidad** [comment]
Changes have been made.

This is the screenshot of the change.
![registerpatient](https://user-images.githubusercontent.com/61451868/82996822-1dfdb380-a038-11ea-9107-003ed9d69eed.png)

This is the code for the change.
[CR008-Register Patient.txt](https://github.com/hapidji96/endgame-dentalia-clinic/files/4687483/CR008-Register.Patient.txt)
