### ISSUE TITLE
Add a new function, which is view appointment schedule

### ISSUE THREAD

**Issue by luqmanhuzaimin** [hapidji96/endgame-dentalia-clinic#20]
Please make the enhancement

**Comment by amirulwidad** [comment]
Changes have been made.

This is the screenshot of the change.
![viewappointment](https://user-images.githubusercontent.com/61451868/82997125-8ea4d000-a038-11ea-8597-245f39e2d003.png)

This is the code for the change.
[CR009-View Appointment.txt](https://github.com/hapidji96/endgame-dentalia-clinic/files/4687539/CR009-View.Appointment.txt)
